import {
  AcUnit,
  AutoAwesome,
  BugReport,
  CircleOutlined,
  WaterDrop,
  Whatshot,
  FlashOnOutlined,
  VisibilityOutlined,
  EnergySavingsLeafOutlined,
  FilterHdr,
  Air,
} from '@mui/icons-material/'

export const typeIcons = {
  bug: BugReport,
  dark: BugReport,
  dragon: BugReport,
  electric: FlashOnOutlined,
  fairy: AutoAwesome,
  fighting: BugReport,
  fire: Whatshot,
  flying: Air,
  ghost: BugReport,
  grass: EnergySavingsLeafOutlined,
  ground: FilterHdr,
  ice: AcUnit,
  normal: CircleOutlined,
  poison: BugReport,
  psychic: VisibilityOutlined,
  rock: BugReport,
  steel: BugReport,
  water: WaterDrop,
}
